name: gauss
version: '0.1.0.0'
category: Math
author: Tim Jäger
maintainer: jger.tm@gmail.com
copyright: 2016 Tim Jäger
license: BSD3
github: jgertm/gauss
ghc-options:
- -Wall
- -fno-warn-type-defaults
- -O2
- -fllvm
default-extensions:
- ExtendedDefaultRules
- FlexibleInstances
- GADTs
- LambdaCase
- MultiParamTypeClasses
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeFamilies
- TypeOperators
dependencies:
- base-noprelude
- classy-prelude

library:
  source-dirs: src
  other-modules:
  exposed-modules:
  - Gauss
  - Prelude
  dependencies:
  - bifunctors
  - integer-gmp
  - uniplate

executables:
  gauss-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gauss

tests:
  gauss-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - gauss
    - tasty
    - tasty-smallcheck
