name: gauss
version: '0.1.0.0'
category: Math
author: Tim Jäger
maintainer: jger.tm@gmail.com
copyright: 2016 Tim Jäger
license: BSD3
github: jgertm/gauss
ghc-options:
- -Wall
- -fno-warn-type-defaults
- -O2
# - -fllvm
default-extensions:
- DeriveGeneric
- ExtendedDefaultRules
- FlexibleContexts
- FlexibleInstances
- GADTs
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- OverloadedLabels
- PartialTypeSignatures
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- TypeOperators
dependencies:
- base
- vector
- universum
- unordered-containers

library:
  source-dirs: src
  other-modules:
  exposed-modules:
  - Dev
  dependencies:
  - bifunctors
  - ghc-prim
  - integer-gmp

executables:
  gauss-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gauss

tests:
  gauss-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - gauss
    - tasty
    - tasty-hunit
    - tasty-smallcheck
