name: gauss
version: '0.1.0.0'
category: Math
author: Tim Jäger
maintainer: jger.tm@gmail.com
copyright: 2016 Tim Jäger
license: BSD3
github: jgertm/gauss
ghc-options:
  - -Wall
  - -fno-warn-type-defaults
  - -O2
  # - -fllvm
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
default-extensions:
  - ApplicativeDo
  - DeriveGeneric
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLabels
  - PartialTypeSignatures
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnicodeSyntax
dependencies:
  - base
  - universum

library:
  source-dirs: src
  other-modules:
  exposed-modules:
    - Dev
    - Examples
  dependencies:
    - bifunctors
    - containers
    - ghc-prim
    - integer-gmp
    - mwc-random
    - primitive
    - unordered-containers
    - vector

executables:
  polly:
    main: Polly.hs
    source-dirs: app
    dependencies: 
      - gauss
      - universum

#   gauss-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#     dependencies:
#     - gauss

tests:
  gauss-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - gauss
      - smallcheck
      - tasty
      - tasty-hunit
      - tasty-smallcheck

benchmarks:
  gauss-bench:
    main: Bench.hs
    source-dirs: bench
    dependencies:
      - criterion
      - gauss
