resolver: lts-8.2
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
nix:
  enable: true
  pure: true
  path: [nixpkgs=/home/tjger/.dotfiles/nixos/nixpkgs]
  packages: [ncurses, git, cabal-install, zlibStatic, binutils, gmp]
