resolver: lts-7.14
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
nix:
  enable: true
  pure: true
  path: [nixpkgs=/home/tjger/work/hacking/nixpkgs]
  packages: [ncurses, git, cabal-install, zlibStatic, binutils]
